// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package envservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnvServiceClient is the client API for EnvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnvServiceClient interface {
	PutEnv(ctx context.Context, in *PutEnvRequest, opts ...grpc.CallOption) (*PutEnvResponse, error)
	GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error)
	ListEnvs(ctx context.Context, in *ListEnvsRequest, opts ...grpc.CallOption) (*ListEnvsResponse, error)
	DelEnv(ctx context.Context, in *DelEnvRequest, opts ...grpc.CallOption) (*DelEnvResponse, error)
	ListCaps(ctx context.Context, in *ListCapsRequest, opts ...grpc.CallOption) (*ListCapsResponse, error)
}

type envServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnvServiceClient(cc grpc.ClientConnInterface) EnvServiceClient {
	return &envServiceClient{cc}
}

func (c *envServiceClient) PutEnv(ctx context.Context, in *PutEnvRequest, opts ...grpc.CallOption) (*PutEnvResponse, error) {
	out := new(PutEnvResponse)
	err := c.cc.Invoke(ctx, "/vela.api.service.envservice.EnvService/PutEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envServiceClient) GetEnv(ctx context.Context, in *GetEnvRequest, opts ...grpc.CallOption) (*GetEnvResponse, error) {
	out := new(GetEnvResponse)
	err := c.cc.Invoke(ctx, "/vela.api.service.envservice.EnvService/GetEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envServiceClient) ListEnvs(ctx context.Context, in *ListEnvsRequest, opts ...grpc.CallOption) (*ListEnvsResponse, error) {
	out := new(ListEnvsResponse)
	err := c.cc.Invoke(ctx, "/vela.api.service.envservice.EnvService/ListEnvs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envServiceClient) DelEnv(ctx context.Context, in *DelEnvRequest, opts ...grpc.CallOption) (*DelEnvResponse, error) {
	out := new(DelEnvResponse)
	err := c.cc.Invoke(ctx, "/vela.api.service.envservice.EnvService/DelEnv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *envServiceClient) ListCaps(ctx context.Context, in *ListCapsRequest, opts ...grpc.CallOption) (*ListCapsResponse, error) {
	out := new(ListCapsResponse)
	err := c.cc.Invoke(ctx, "/vela.api.service.envservice.EnvService/ListCaps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnvServiceServer is the server API for EnvService service.
// All implementations should embed UnimplementedEnvServiceServer
// for forward compatibility
type EnvServiceServer interface {
	PutEnv(context.Context, *PutEnvRequest) (*PutEnvResponse, error)
	GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error)
	ListEnvs(context.Context, *ListEnvsRequest) (*ListEnvsResponse, error)
	DelEnv(context.Context, *DelEnvRequest) (*DelEnvResponse, error)
	ListCaps(context.Context, *ListCapsRequest) (*ListCapsResponse, error)
}

// UnimplementedEnvServiceServer should be embedded to have forward compatible implementations.
type UnimplementedEnvServiceServer struct {
}

func (UnimplementedEnvServiceServer) PutEnv(context.Context, *PutEnvRequest) (*PutEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutEnv not implemented")
}
func (UnimplementedEnvServiceServer) GetEnv(context.Context, *GetEnvRequest) (*GetEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnv not implemented")
}
func (UnimplementedEnvServiceServer) ListEnvs(context.Context, *ListEnvsRequest) (*ListEnvsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvs not implemented")
}
func (UnimplementedEnvServiceServer) DelEnv(context.Context, *DelEnvRequest) (*DelEnvResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelEnv not implemented")
}
func (UnimplementedEnvServiceServer) ListCaps(context.Context, *ListCapsRequest) (*ListCapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCaps not implemented")
}

// UnsafeEnvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnvServiceServer will
// result in compilation errors.
type UnsafeEnvServiceServer interface {
	mustEmbedUnimplementedEnvServiceServer()
}

func RegisterEnvServiceServer(s grpc.ServiceRegistrar, srv EnvServiceServer) {
	s.RegisterService(&EnvService_ServiceDesc, srv)
}

func _EnvService_PutEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvServiceServer).PutEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vela.api.service.envservice.EnvService/PutEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvServiceServer).PutEnv(ctx, req.(*PutEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvService_GetEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvServiceServer).GetEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vela.api.service.envservice.EnvService/GetEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvServiceServer).GetEnv(ctx, req.(*GetEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvService_ListEnvs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvServiceServer).ListEnvs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vela.api.service.envservice.EnvService/ListEnvs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvServiceServer).ListEnvs(ctx, req.(*ListEnvsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvService_DelEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvServiceServer).DelEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vela.api.service.envservice.EnvService/DelEnv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvServiceServer).DelEnv(ctx, req.(*DelEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnvService_ListCaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnvServiceServer).ListCaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vela.api.service.envservice.EnvService/ListCaps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnvServiceServer).ListCaps(ctx, req.(*ListCapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnvService_ServiceDesc is the grpc.ServiceDesc for EnvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vela.api.service.envservice.EnvService",
	HandlerType: (*EnvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEnv",
			Handler:    _EnvService_PutEnv_Handler,
		},
		{
			MethodName: "GetEnv",
			Handler:    _EnvService_GetEnv_Handler,
		},
		{
			MethodName: "ListEnvs",
			Handler:    _EnvService_ListEnvs_Handler,
		},
		{
			MethodName: "DelEnv",
			Handler:    _EnvService_DelEnv_Handler,
		},
		{
			MethodName: "ListCaps",
			Handler:    _EnvService_ListCaps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/envservice/service.proto",
}
