// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pkg/proto/envservice/service.proto

package envservice

import (
	proto "github.com/golang/protobuf/proto"
	model "github.com/oam-dev/velacp/pkg/datastore/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PutEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Env *model.Environment `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *PutEnvRequest) Reset() {
	*x = PutEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEnvRequest) ProtoMessage() {}

func (x *PutEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEnvRequest.ProtoReflect.Descriptor instead.
func (*PutEnvRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *PutEnvRequest) GetEnv() *model.Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

type PutEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutEnvResponse) Reset() {
	*x = PutEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutEnvResponse) ProtoMessage() {}

func (x *PutEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutEnvResponse.ProtoReflect.Descriptor instead.
func (*PutEnvResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{1}
}

type GetEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetEnvRequest) Reset() {
	*x = GetEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvRequest) ProtoMessage() {}

func (x *GetEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvRequest.ProtoReflect.Descriptor instead.
func (*GetEnvRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Env *model.Environment `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
}

func (x *GetEnvResponse) Reset() {
	*x = GetEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvResponse) ProtoMessage() {}

func (x *GetEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvResponse.ProtoReflect.Descriptor instead.
func (*GetEnvResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEnvResponse) GetEnv() *model.Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

type ListEnvsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEnvsRequest) Reset() {
	*x = ListEnvsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEnvsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvsRequest) ProtoMessage() {}

func (x *ListEnvsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvsRequest.ProtoReflect.Descriptor instead.
func (*ListEnvsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{4}
}

type ListEnvsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envs []*model.Environment `protobuf:"bytes,1,rep,name=envs,proto3" json:"envs,omitempty"`
}

func (x *ListEnvsResponse) Reset() {
	*x = ListEnvsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEnvsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvsResponse) ProtoMessage() {}

func (x *ListEnvsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvsResponse.ProtoReflect.Descriptor instead.
func (*ListEnvsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListEnvsResponse) GetEnvs() []*model.Environment {
	if x != nil {
		return x.Envs
	}
	return nil
}

type DelEnvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DelEnvRequest) Reset() {
	*x = DelEnvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelEnvRequest) ProtoMessage() {}

func (x *DelEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelEnvRequest.ProtoReflect.Descriptor instead.
func (*DelEnvRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{6}
}

func (x *DelEnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DelEnvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelEnvResponse) Reset() {
	*x = DelEnvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelEnvResponse) ProtoMessage() {}

func (x *DelEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelEnvResponse.ProtoReflect.Descriptor instead.
func (*DelEnvResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{7}
}

type ListCapsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvName string `protobuf:"bytes,1,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
}

func (x *ListCapsRequest) Reset() {
	*x = ListCapsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCapsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapsRequest) ProtoMessage() {}

func (x *ListCapsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapsRequest.ProtoReflect.Descriptor instead.
func (*ListCapsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCapsRequest) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

type ListCapsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caps []*model.Capability `protobuf:"bytes,1,rep,name=caps,proto3" json:"caps,omitempty"`
}

func (x *ListCapsResponse) Reset() {
	*x = ListCapsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_envservice_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCapsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapsResponse) ProtoMessage() {}

func (x *ListCapsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_envservice_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapsResponse.ProtoReflect.Descriptor instead.
func (*ListCapsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_envservice_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListCapsResponse) GetCaps() []*model.Capability {
	if x != nil {
		return x.Caps
	}
	return nil
}

var File_pkg_proto_envservice_service_proto protoreflect.FileDescriptor

var file_pkg_proto_envservice_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x76, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x1a, 0x25, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0d, 0x50,
	0x75, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x03,
	0x65, 0x6e, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x65, 0x6c, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x22, 0x10, 0x0a, 0x0e, 0x50,
	0x75, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x76, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x65, 0x6e,
	0x76, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x76, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x42, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x63, 0x61, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x04,
	0x63, 0x61, 0x70, 0x73, 0x32, 0x91, 0x04, 0x0a, 0x0a, 0x45, 0x6e, 0x76, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x63, 0x0a, 0x06, 0x50, 0x75, 0x74, 0x45, 0x6e, 0x76, 0x12, 0x2a, 0x2e,
	0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x45,
	0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x76, 0x65, 0x6c, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x76, 0x12, 0x2a, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b,
	0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x73, 0x12, 0x2c, 0x2e, 0x76, 0x65, 0x6c, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x76, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x45,
	0x6e, 0x76, 0x12, 0x2a, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b,
	0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x45, 0x6e, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x70, 0x73, 0x12, 0x2c, 0x2e, 0x76, 0x65, 0x6c, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x76, 0x65, 0x6c, 0x61, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6e, 0x76, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x70, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x61, 0x6d, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x76,
	0x65, 0x6c, 0x61, 0x63, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x6e, 0x76, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_proto_envservice_service_proto_rawDescOnce sync.Once
	file_pkg_proto_envservice_service_proto_rawDescData = file_pkg_proto_envservice_service_proto_rawDesc
)

func file_pkg_proto_envservice_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_envservice_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_envservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_envservice_service_proto_rawDescData)
	})
	return file_pkg_proto_envservice_service_proto_rawDescData
}

var file_pkg_proto_envservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_proto_envservice_service_proto_goTypes = []interface{}{
	(*PutEnvRequest)(nil),     // 0: vela.api.service.envservice.PutEnvRequest
	(*PutEnvResponse)(nil),    // 1: vela.api.service.envservice.PutEnvResponse
	(*GetEnvRequest)(nil),     // 2: vela.api.service.envservice.GetEnvRequest
	(*GetEnvResponse)(nil),    // 3: vela.api.service.envservice.GetEnvResponse
	(*ListEnvsRequest)(nil),   // 4: vela.api.service.envservice.ListEnvsRequest
	(*ListEnvsResponse)(nil),  // 5: vela.api.service.envservice.ListEnvsResponse
	(*DelEnvRequest)(nil),     // 6: vela.api.service.envservice.DelEnvRequest
	(*DelEnvResponse)(nil),    // 7: vela.api.service.envservice.DelEnvResponse
	(*ListCapsRequest)(nil),   // 8: vela.api.service.envservice.ListCapsRequest
	(*ListCapsResponse)(nil),  // 9: vela.api.service.envservice.ListCapsResponse
	(*model.Environment)(nil), // 10: vela.api.model.Environment
	(*model.Capability)(nil),  // 11: vela.api.model.Capability
}
var file_pkg_proto_envservice_service_proto_depIdxs = []int32{
	10, // 0: vela.api.service.envservice.PutEnvRequest.env:type_name -> vela.api.model.Environment
	10, // 1: vela.api.service.envservice.GetEnvResponse.env:type_name -> vela.api.model.Environment
	10, // 2: vela.api.service.envservice.ListEnvsResponse.envs:type_name -> vela.api.model.Environment
	11, // 3: vela.api.service.envservice.ListCapsResponse.caps:type_name -> vela.api.model.Capability
	0,  // 4: vela.api.service.envservice.EnvService.PutEnv:input_type -> vela.api.service.envservice.PutEnvRequest
	2,  // 5: vela.api.service.envservice.EnvService.GetEnv:input_type -> vela.api.service.envservice.GetEnvRequest
	4,  // 6: vela.api.service.envservice.EnvService.ListEnvs:input_type -> vela.api.service.envservice.ListEnvsRequest
	6,  // 7: vela.api.service.envservice.EnvService.DelEnv:input_type -> vela.api.service.envservice.DelEnvRequest
	8,  // 8: vela.api.service.envservice.EnvService.ListCaps:input_type -> vela.api.service.envservice.ListCapsRequest
	1,  // 9: vela.api.service.envservice.EnvService.PutEnv:output_type -> vela.api.service.envservice.PutEnvResponse
	3,  // 10: vela.api.service.envservice.EnvService.GetEnv:output_type -> vela.api.service.envservice.GetEnvResponse
	5,  // 11: vela.api.service.envservice.EnvService.ListEnvs:output_type -> vela.api.service.envservice.ListEnvsResponse
	7,  // 12: vela.api.service.envservice.EnvService.DelEnv:output_type -> vela.api.service.envservice.DelEnvResponse
	9,  // 13: vela.api.service.envservice.EnvService.ListCaps:output_type -> vela.api.service.envservice.ListCapsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_envservice_service_proto_init() }
func file_pkg_proto_envservice_service_proto_init() {
	if File_pkg_proto_envservice_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_envservice_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEnvsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEnvsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelEnvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelEnvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCapsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_envservice_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCapsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_envservice_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_envservice_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_envservice_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_envservice_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_envservice_service_proto = out.File
	file_pkg_proto_envservice_service_proto_rawDesc = nil
	file_pkg_proto_envservice_service_proto_goTypes = nil
	file_pkg_proto_envservice_service_proto_depIdxs = nil
}
